### ISSUE TITLE
db를 읽을 때 특정 도메인에서만 접근할 수 있도록 제한

### ISSUE THREAD

**Issue by baumstern** [ethcon-korea/qf-round#8]
supabase에서 호스팅하는 DB로의 접근을 qf.ethcon.kr 에서 오는 요청만 허용하도록 제한합니다

**Comment by yuhatown** [comment]
@gurrpi 
supabase CLI 를 사용하면 되는 것 같습니다. 
CLI를 사용할 때 access token이 필요합니다. 
이건 디엠으로 남겨드릴게요.


CLI: https://supabase.com/docs/guides/cli 
Network: https://supabase.com/docs/guides/platform/network-restrictions

**Comment by baumstern** [comment]
> 

감사합니다! CIDR로 접근을 제어할 수 있군요. 저희 프론트가 Cloudflare를 이용해서 배포하고 있는데 [여기](https://www.cloudflare.com/en-gb/ips/)에 따르면 아래 CIDR range를 적용하면 될 것 같아보입니다:

```

    103.21.244.0/22
    103.22.200.0/22
    103.31.4.0/22
    104.16.0.0/13
    104.24.0.0/14
    108.162.192.0/18
    131.0.72.0/22
    141.101.64.0/18
    162.158.0.0/15
    172.64.0.0/13
    173.245.48.0/20
    188.114.96.0/20
    190.93.240.0/20
    197.234.240.0/22
    198.41.128.0/17
```

**Comment by baumstern** [comment]
음 근데 요청은 클라이언트 ip로 나갈꺼라서 다른 방법을 찾아봐야될 것 같군요..
